// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    connection_id,
    provider_account_id,
    name,
    bank_type,
    mask,
    kind,
    kind_overridden,
    counts_as_savings,
    savings_overridden,
    balance_amount,
    balance_currency,
    balance_known,
    state,
    last_synced_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at, mask, custom_name, statement_balance, statement_issued_at, statement_due_at, payment_schedule_mode, payment_schedule_offset_days
`

type CreateAccountParams struct {
	ID                string
	ConnectionID      string
	ProviderAccountID string
	Name              string
	BankType          string
	Mask              string
	Kind              string
	KindOverridden    int64
	CountsAsSavings   int64
	SavingsOverridden int64
	BalanceAmount     float64
	BalanceCurrency   string
	BalanceKnown      int64
	State             string
	LastSyncedAt      sql.NullTime
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.ConnectionID,
		arg.ProviderAccountID,
		arg.Name,
		arg.BankType,
		arg.Mask,
		arg.Kind,
		arg.KindOverridden,
		arg.CountsAsSavings,
		arg.SavingsOverridden,
		arg.BalanceAmount,
		arg.BalanceCurrency,
		arg.BalanceKnown,
		arg.State,
		arg.LastSyncedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mask,
		&i.CustomName,
		&i.StatementBalance,
		&i.StatementIssuedAt,
		&i.StatementDueAt,
		&i.PaymentScheduleMode,
		&i.PaymentScheduleOffsetDays,
	)
	return i, err
}

const deleteAccountsByConnection = `-- name: DeleteAccountsByConnection :exec
DELETE FROM accounts
WHERE connection_id = ?
`

func (q *Queries) DeleteAccountsByConnection(ctx context.Context, connectionID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountsByConnection, connectionID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at, mask, custom_name, statement_balance, statement_issued_at, statement_due_at, payment_schedule_mode, payment_schedule_offset_days FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mask,
		&i.CustomName,
		&i.StatementBalance,
		&i.StatementIssuedAt,
		&i.StatementDueAt,
		&i.PaymentScheduleMode,
		&i.PaymentScheduleOffsetDays,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at, mask, custom_name, statement_balance, statement_issued_at, statement_due_at, payment_schedule_mode, payment_schedule_offset_days FROM accounts
ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.ProviderAccountID,
			&i.Name,
			&i.BankType,
			&i.Kind,
			&i.KindOverridden,
			&i.CountsAsSavings,
			&i.SavingsOverridden,
			&i.BalanceAmount,
			&i.BalanceCurrency,
			&i.BalanceKnown,
			&i.State,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mask,
			&i.CustomName,
			&i.StatementBalance,
			&i.StatementIssuedAt,
			&i.StatementDueAt,
			&i.PaymentScheduleMode,
			&i.PaymentScheduleOffsetDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByConnection = `-- name: ListAccountsByConnection :many
SELECT id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at, mask, custom_name, statement_balance, statement_issued_at, statement_due_at, payment_schedule_mode, payment_schedule_offset_days FROM accounts
WHERE connection_id = ?
ORDER BY created_at
`

func (q *Queries) ListAccountsByConnection(ctx context.Context, connectionID string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.ProviderAccountID,
			&i.Name,
			&i.BankType,
			&i.Kind,
			&i.KindOverridden,
			&i.CountsAsSavings,
			&i.SavingsOverridden,
			&i.BalanceAmount,
			&i.BalanceCurrency,
			&i.BalanceKnown,
			&i.State,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mask,
			&i.CustomName,
			&i.StatementBalance,
			&i.StatementIssuedAt,
			&i.StatementDueAt,
			&i.PaymentScheduleMode,
			&i.PaymentScheduleOffsetDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name               = ?,
    bank_type          = ?,
    mask               = ?,
    kind               = ?,
    kind_overridden    = ?,
    counts_as_savings  = ?,
    savings_overridden = ?,
    balance_amount     = ?,
    balance_currency   = ?,
    balance_known      = ?,
    state              = ?,
    last_synced_at     = ?,
    updated_at         = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at, mask, custom_name, statement_balance, statement_issued_at, statement_due_at, payment_schedule_mode, payment_schedule_offset_days
`

type UpdateAccountParams struct {
	Name              string
	BankType          string
	Mask              string
	Kind              string
	KindOverridden    int64
	CountsAsSavings   int64
	SavingsOverridden int64
	BalanceAmount     float64
	BalanceCurrency   string
	BalanceKnown      int64
	State             string
	LastSyncedAt      sql.NullTime
	ID                string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.BankType,
		arg.Mask,
		arg.Kind,
		arg.KindOverridden,
		arg.CountsAsSavings,
		arg.SavingsOverridden,
		arg.BalanceAmount,
		arg.BalanceCurrency,
		arg.BalanceKnown,
		arg.State,
		arg.LastSyncedAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mask,
		&i.CustomName,
		&i.StatementBalance,
		&i.StatementIssuedAt,
		&i.StatementDueAt,
		&i.PaymentScheduleMode,
		&i.PaymentScheduleOffsetDays,
	)
	return i, err
}

const updateAccountCustomName = `-- name: UpdateAccountCustomName :one
UPDATE accounts
SET custom_name = ?,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at, mask, custom_name, statement_balance, statement_issued_at, statement_due_at, payment_schedule_mode, payment_schedule_offset_days
`

type UpdateAccountCustomNameParams struct {
	CustomName sql.NullString
	ID         string
}

func (q *Queries) UpdateAccountCustomName(ctx context.Context, arg UpdateAccountCustomNameParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountCustomName, arg.CustomName, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mask,
		&i.CustomName,
		&i.StatementBalance,
		&i.StatementIssuedAt,
		&i.StatementDueAt,
		&i.PaymentScheduleMode,
		&i.PaymentScheduleOffsetDays,
	)
	return i, err
}

const updateAccountPaymentSchedule = `-- name: UpdateAccountPaymentSchedule :one
UPDATE accounts
SET payment_schedule_mode        = ?,
    payment_schedule_offset_days = ?,
    updated_at                   = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at, mask, custom_name, statement_balance, statement_issued_at, statement_due_at, payment_schedule_mode, payment_schedule_offset_days
`

type UpdateAccountPaymentScheduleParams struct {
	PaymentScheduleMode       string
	PaymentScheduleOffsetDays int64
	ID                        string
}

// User-owned: when this card is paid. Sync never calls this.
func (q *Queries) UpdateAccountPaymentSchedule(ctx context.Context, arg UpdateAccountPaymentScheduleParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountPaymentSchedule, arg.PaymentScheduleMode, arg.PaymentScheduleOffsetDays, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mask,
		&i.CustomName,
		&i.StatementBalance,
		&i.StatementIssuedAt,
		&i.StatementDueAt,
		&i.PaymentScheduleMode,
		&i.PaymentScheduleOffsetDays,
	)
	return i, err
}

const updateAccountStatement = `-- name: UpdateAccountStatement :one
UPDATE accounts
SET statement_balance   = ?,
    statement_issued_at = ?,
    statement_due_at    = ?,
    updated_at          = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at, mask, custom_name, statement_balance, statement_issued_at, statement_due_at, payment_schedule_mode, payment_schedule_offset_days
`

type UpdateAccountStatementParams struct {
	StatementBalance  sql.NullFloat64
	StatementIssuedAt sql.NullTime
	StatementDueAt    sql.NullTime
	ID                string
}

// Sync-owned: the billing-cycle facts the bank reported. Deliberately separate
// from UpdateAccount so a sync can never write the user's payment schedule, and
// from the schedule update so a user edit can never write statement figures.
func (q *Queries) UpdateAccountStatement(ctx context.Context, arg UpdateAccountStatementParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountStatement,
		arg.StatementBalance,
		arg.StatementIssuedAt,
		arg.StatementDueAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mask,
		&i.CustomName,
		&i.StatementBalance,
		&i.StatementIssuedAt,
		&i.StatementDueAt,
		&i.PaymentScheduleMode,
		&i.PaymentScheduleOffsetDays,
	)
	return i, err
}
