// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    connection_id,
    provider_account_id,
    name,
    bank_type,
    kind,
    kind_overridden,
    counts_as_savings,
    savings_overridden,
    balance_amount,
    balance_currency,
    balance_known,
    state,
    last_synced_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at
`

type CreateAccountParams struct {
	ID                string
	ConnectionID      string
	ProviderAccountID string
	Name              string
	BankType          string
	Kind              string
	KindOverridden    int64
	CountsAsSavings   int64
	SavingsOverridden int64
	BalanceAmount     float64
	BalanceCurrency   string
	BalanceKnown      int64
	State             string
	LastSyncedAt      sql.NullTime
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.ConnectionID,
		arg.ProviderAccountID,
		arg.Name,
		arg.BankType,
		arg.Kind,
		arg.KindOverridden,
		arg.CountsAsSavings,
		arg.SavingsOverridden,
		arg.BalanceAmount,
		arg.BalanceCurrency,
		arg.BalanceKnown,
		arg.State,
		arg.LastSyncedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at FROM accounts
ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.ProviderAccountID,
			&i.Name,
			&i.BankType,
			&i.Kind,
			&i.KindOverridden,
			&i.CountsAsSavings,
			&i.SavingsOverridden,
			&i.BalanceAmount,
			&i.BalanceCurrency,
			&i.BalanceKnown,
			&i.State,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByConnection = `-- name: ListAccountsByConnection :many
SELECT id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at FROM accounts
WHERE connection_id = ?
ORDER BY created_at
`

func (q *Queries) ListAccountsByConnection(ctx context.Context, connectionID string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.ProviderAccountID,
			&i.Name,
			&i.BankType,
			&i.Kind,
			&i.KindOverridden,
			&i.CountsAsSavings,
			&i.SavingsOverridden,
			&i.BalanceAmount,
			&i.BalanceCurrency,
			&i.BalanceKnown,
			&i.State,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name               = ?,
    bank_type          = ?,
    kind               = ?,
    kind_overridden    = ?,
    counts_as_savings  = ?,
    savings_overridden = ?,
    balance_amount     = ?,
    balance_currency   = ?,
    balance_known      = ?,
    state              = ?,
    last_synced_at     = ?,
    updated_at         = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, connection_id, provider_account_id, name, bank_type, kind, kind_overridden, counts_as_savings, savings_overridden, balance_amount, balance_currency, balance_known, state, last_synced_at, created_at, updated_at
`

type UpdateAccountParams struct {
	Name              string
	BankType          string
	Kind              string
	KindOverridden    int64
	CountsAsSavings   int64
	SavingsOverridden int64
	BalanceAmount     float64
	BalanceCurrency   string
	BalanceKnown      int64
	State             string
	LastSyncedAt      sql.NullTime
	ID                string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.BankType,
		arg.Kind,
		arg.KindOverridden,
		arg.CountsAsSavings,
		arg.SavingsOverridden,
		arg.BalanceAmount,
		arg.BalanceCurrency,
		arg.BalanceKnown,
		arg.State,
		arg.LastSyncedAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ProviderAccountID,
		&i.Name,
		&i.BankType,
		&i.Kind,
		&i.KindOverridden,
		&i.CountsAsSavings,
		&i.SavingsOverridden,
		&i.BalanceAmount,
		&i.BalanceCurrency,
		&i.BalanceKnown,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
