// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package sqlc

import (
	"context"
)

const createCategoryLimit = `-- name: CreateCategoryLimit :exec
INSERT INTO budget_category_limits (
    category_id,
    limit_amount
) VALUES (
    ?, ?
)
`

type CreateCategoryLimitParams struct {
	CategoryID  string
	LimitAmount float64
}

func (q *Queries) CreateCategoryLimit(ctx context.Context, arg CreateCategoryLimitParams) error {
	_, err := q.db.ExecContext(ctx, createCategoryLimit, arg.CategoryID, arg.LimitAmount)
	return err
}

const deleteAllCategoryLimits = `-- name: DeleteAllCategoryLimits :exec
DELETE FROM budget_category_limits
`

func (q *Queries) DeleteAllCategoryLimits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCategoryLimits)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT id, income_target, savings_target, created_at, updated_at FROM budget
WHERE id = ?
`

func (q *Queries) GetBudget(ctx context.Context, id string) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.IncomeTarget,
		&i.SavingsTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryLimits = `-- name: ListCategoryLimits :many
SELECT category_id, limit_amount FROM budget_category_limits
ORDER BY category_id
`

func (q *Queries) ListCategoryLimits(ctx context.Context) ([]BudgetCategoryLimit, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetCategoryLimit
	for rows.Next() {
		var i BudgetCategoryLimit
		if err := rows.Scan(&i.CategoryID, &i.LimitAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budget (
    id,
    income_target,
    savings_target
) VALUES (
    ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    income_target  = excluded.income_target,
    savings_target = excluded.savings_target,
    updated_at     = CURRENT_TIMESTAMP
RETURNING id, income_target, savings_target, created_at, updated_at
`

type UpsertBudgetParams struct {
	ID            string
	IncomeTarget  float64
	SavingsTarget float64
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, upsertBudget, arg.ID, arg.IncomeTarget, arg.SavingsTarget)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.IncomeTarget,
		&i.SavingsTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
