// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package sqlc

import (
	"context"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (
    id, item_id, access_token, state
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, item_id, access_token, state, created_at, updated_at
`

type CreateConnectionParams struct {
	ID          string
	ItemID      string
	AccessToken string
	State       string
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnection,
		arg.ID,
		arg.ItemID,
		arg.AccessToken,
		arg.State,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.AccessToken,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnection = `-- name: GetConnection :one
SELECT id, item_id, access_token, state, created_at, updated_at FROM connections
WHERE id = ?
`

func (q *Queries) GetConnection(ctx context.Context, id string) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.AccessToken,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectionByItemID = `-- name: GetConnectionByItemID :one
SELECT id, item_id, access_token, state, created_at, updated_at FROM connections
WHERE item_id = ?
`

func (q *Queries) GetConnectionByItemID(ctx context.Context, itemID string) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnectionByItemID, itemID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.AccessToken,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, item_id, access_token, state, created_at, updated_at FROM connections
ORDER BY created_at
`

func (q *Queries) ListConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.AccessToken,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnection = `-- name: UpdateConnection :one
UPDATE connections
SET item_id      = ?,
    access_token = ?,
    state        = ?,
    updated_at   = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, item_id, access_token, state, created_at, updated_at
`

type UpdateConnectionParams struct {
	ItemID      string
	AccessToken string
	State       string
	ID          string
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, updateConnection,
		arg.ItemID,
		arg.AccessToken,
		arg.State,
		arg.ID,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.AccessToken,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
