// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchant_logos.sql

package sqlc

import (
	"context"
)

const getMerchantLogo = `-- name: GetMerchantLogo :one
SELECT content_type, image_bytes
FROM merchant_logo_cache
WHERE logo_key = ? AND image_bytes IS NOT NULL
`

type GetMerchantLogoRow struct {
	ContentType string
	ImageBytes  []byte
}

// The cached image bytes and content type for a positively cached logo key. A
// negative entry (NULL image_bytes) is excluded, so a cache miss and a negative key
// both return no row: the image endpoint serves bytes only for a positively cached
// key, and never for one recorded as having no usable logo.
func (q *Queries) GetMerchantLogo(ctx context.Context, logoKey string) (GetMerchantLogoRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchantLogo, logoKey)
	var i GetMerchantLogoRow
	err := row.Scan(&i.ContentType, &i.ImageBytes)
	return i, err
}

const listCachedLogoKeys = `-- name: ListCachedLogoKeys :many
SELECT logo_key FROM merchant_logo_cache
`

// Every logo key already in the cache, positive or negative: the set the warm step
// skips so no already-attempted merchant is fetched again on a later sync.
func (q *Queries) ListCachedLogoKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCachedLogoKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var logo_key string
		if err := rows.Scan(&logo_key); err != nil {
			return nil, err
		}
		items = append(items, logo_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantLogoURLsByRecency = `-- name: ListMerchantLogoURLsByRecency :many
SELECT logo_url
FROM transactions
WHERE logo_url != ''
GROUP BY logo_url
ORDER BY MAX(date) DESC
`

// Each distinct non-empty merchant logo URL across the whole stored transaction set,
// most recent first by the merchant's latest transaction date. The warm step walks
// this order, skips already-cached keys, and fetches only a bounded batch, so a large
// backlog drains over successive syncs with the current month's merchants warmed first.
func (q *Queries) ListMerchantLogoURLsByRecency(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMerchantLogoURLsByRecency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var logo_url string
		if err := rows.Scan(&logo_url); err != nil {
			return nil, err
		}
		items = append(items, logo_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositiveLogoKeys = `-- name: ListPositiveLogoKeys :many
SELECT logo_key FROM merchant_logo_cache WHERE image_bytes IS NOT NULL
`

// Every positively cached logo key (a stored image). The read model consults this set
// to fill a row's served logo URL only when the logo is actually cached, so a miss or
// a negative entry leaves the row without a logo (its category glyph shows instead).
func (q *Queries) ListPositiveLogoKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPositiveLogoKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var logo_key string
		if err := rows.Scan(&logo_key); err != nil {
			return nil, err
		}
		items = append(items, logo_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putMerchantLogo = `-- name: PutMerchantLogo :exec
INSERT INTO merchant_logo_cache (logo_key, logo_url, content_type, image_bytes)
VALUES (?, ?, ?, ?)
ON CONFLICT (logo_key) DO UPDATE SET
    logo_url     = excluded.logo_url,
    content_type = excluded.content_type,
    image_bytes  = excluded.image_bytes,
    updated_at   = CURRENT_TIMESTAMP
`

type PutMerchantLogoParams struct {
	LogoKey     string
	LogoUrl     string
	ContentType string
	ImageBytes  []byte
}

// Record a positively cached logo: its bytes and stored content type under the URL's
// content-hash key. Idempotent by key so a re-warm rewrites the same key in place.
func (q *Queries) PutMerchantLogo(ctx context.Context, arg PutMerchantLogoParams) error {
	_, err := q.db.ExecContext(ctx, putMerchantLogo,
		arg.LogoKey,
		arg.LogoUrl,
		arg.ContentType,
		arg.ImageBytes,
	)
	return err
}

const putMerchantLogoMiss = `-- name: PutMerchantLogoMiss :exec
INSERT INTO merchant_logo_cache (logo_key, logo_url, content_type, image_bytes)
VALUES (?, ?, '', NULL)
ON CONFLICT (logo_key) DO NOTHING
`

type PutMerchantLogoMissParams struct {
	LogoKey string
	LogoUrl string
}

// Record a negative cache entry: a logo URL that yielded no usable logo. image_bytes
// stays NULL and content_type empty, so the warm step attempts the key exactly once
// and the image endpoint never serves it. DO NOTHING on conflict so it never clobbers
// an existing positive entry for the same key.
func (q *Queries) PutMerchantLogoMiss(ctx context.Context, arg PutMerchantLogoMissParams) error {
	_, err := q.db.ExecContext(ctx, putMerchantLogoMiss, arg.LogoKey, arg.LogoUrl)
	return err
}
