// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Account struct {
	ID                string
	ConnectionID      string
	ProviderAccountID string
	Name              string
	BankType          string
	Kind              string
	KindOverridden    int64
	CountsAsSavings   int64
	SavingsOverridden int64
	BalanceAmount     float64
	BalanceCurrency   string
	BalanceKnown      int64
	State             string
	LastSyncedAt      sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Connection struct {
	ID          string
	ItemID      string
	AccessToken string
	State       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}
