// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Account struct {
	ID                string
	ConnectionID      string
	ProviderAccountID string
	Name              string
	BankType          string
	Kind              string
	KindOverridden    int64
	CountsAsSavings   int64
	SavingsOverridden int64
	BalanceAmount     float64
	BalanceCurrency   string
	BalanceKnown      int64
	State             string
	LastSyncedAt      sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Mask              string
	CustomName        sql.NullString
}

type Budget struct {
	ID            string
	IncomeTarget  float64
	SavingsTarget float64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type BudgetCategoryLimit struct {
	CategoryID  string
	LimitAmount float64
}

type Category struct {
	ID        string
	Name      string
	Builtin   int64
	Archived  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Connection struct {
	ID          string
	ItemID      string
	AccessToken string
	State       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type MerchantLogoCache struct {
	LogoKey     string
	LogoUrl     string
	ContentType string
	ImageBytes  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Rule struct {
	ID                string
	MerchantSubstring string
	Classification    string
	CategoryID        sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type SweepRecommendation struct {
	ID                    string
	Kind                  string
	CurrentChecking       sql.NullFloat64
	CurrentSavings        sql.NullFloat64
	SavingsUnknown        int64
	TotalSpendingBudget   float64
	MtdSpending           float64
	SavingsTarget         float64
	MtdSavingsContributed float64
	Reserve               float64
	FixedSafetyMargin     float64
	SuggestedSweep        float64
	Direction             string
	Reasons               string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Transaction struct {
	ID                            string
	AccountID                     string
	Date                          time.Time
	AmountAmount                  float64
	AmountCurrency                string
	Merchant                      string
	Counterparty                  string
	CategoryPrimary               string
	CategoryDetailed              string
	Status                        string
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
	Classification                string
	CategoryID                    sql.NullString
	CategorizationOverridden      int64
	TransferDestinationAccountID  sql.NullString
	TransferSubtype               string
	TransferDestinationOverridden int64
	Description                   string
	MerchantEntityID              string
	LogoUrl                       string
	Website                       string
	PaymentChannel                string
	CategoryConfidence            string
	AuthorizedDate                sql.NullTime
	Datetime                      sql.NullTime
	AuthorizedDatetime            sql.NullTime
	Counterparties                string
}

type TransactionSyncState struct {
	ConnectionID string
	Cursor       string
	UpdatedAt    time.Time
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
