// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (
    id,
    merchant_substring,
    classification,
    category_id
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, merchant_substring, classification, category_id, created_at, updated_at
`

type CreateRuleParams struct {
	ID                string
	MerchantSubstring string
	Classification    string
	CategoryID        sql.NullString
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, createRule,
		arg.ID,
		arg.MerchantSubstring,
		arg.Classification,
		arg.CategoryID,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.MerchantSubstring,
		&i.Classification,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules
WHERE id = ?
`

func (q *Queries) DeleteRule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, merchant_substring, classification, category_id, created_at, updated_at FROM rules
WHERE id = ?
`

func (q *Queries) GetRule(ctx context.Context, id string) (Rule, error) {
	row := q.db.QueryRowContext(ctx, getRule, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.MerchantSubstring,
		&i.Classification,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRules = `-- name: ListRules :many
SELECT id, merchant_substring, classification, category_id, created_at, updated_at FROM rules
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.MerchantSubstring,
			&i.Classification,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET merchant_substring = ?,
    classification     = ?,
    category_id        = ?,
    updated_at         = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, merchant_substring, classification, category_id, created_at, updated_at
`

type UpdateRuleParams struct {
	MerchantSubstring string
	Classification    string
	CategoryID        sql.NullString
	ID                string
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, updateRule,
		arg.MerchantSubstring,
		arg.Classification,
		arg.CategoryID,
		arg.ID,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.MerchantSubstring,
		&i.Classification,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
