// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteScheduleItem = `-- name: DeleteScheduleItem :exec
DELETE FROM schedule_items
WHERE id = ?
`

func (q *Queries) DeleteScheduleItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleItem, id)
	return err
}

const insertScheduleItem = `-- name: InsertScheduleItem :exec
INSERT INTO schedule_items (
    id,
    name,
    direction,
    amount,
    cadence,
    day_of_month,
    anchor_date,
    active
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertScheduleItemParams struct {
	ID         string
	Name       string
	Direction  string
	Amount     float64
	Cadence    string
	DayOfMonth sql.NullInt64
	AnchorDate sql.NullTime
	Active     int64
}

func (q *Queries) InsertScheduleItem(ctx context.Context, arg InsertScheduleItemParams) error {
	_, err := q.db.ExecContext(ctx, insertScheduleItem,
		arg.ID,
		arg.Name,
		arg.Direction,
		arg.Amount,
		arg.Cadence,
		arg.DayOfMonth,
		arg.AnchorDate,
		arg.Active,
	)
	return err
}

const listScheduleItems = `-- name: ListScheduleItems :many
SELECT id, name, direction, amount, cadence, day_of_month, anchor_date, active, created_at, updated_at FROM schedule_items
ORDER BY name COLLATE NOCASE, rowid
`

func (q *Queries) ListScheduleItems(ctx context.Context) ([]ScheduleItem, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleItem
	for rows.Next() {
		var i ScheduleItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Direction,
			&i.Amount,
			&i.Cadence,
			&i.DayOfMonth,
			&i.AnchorDate,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleItem = `-- name: UpdateScheduleItem :exec
UPDATE schedule_items
SET name         = ?,
    direction    = ?,
    amount       = ?,
    cadence      = ?,
    day_of_month = ?,
    anchor_date  = ?,
    active       = ?,
    updated_at   = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScheduleItemParams struct {
	Name       string
	Direction  string
	Amount     float64
	Cadence    string
	DayOfMonth sql.NullInt64
	AnchorDate sql.NullTime
	Active     int64
	ID         string
}

func (q *Queries) UpdateScheduleItem(ctx context.Context, arg UpdateScheduleItemParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleItem,
		arg.Name,
		arg.Direction,
		arg.Amount,
		arg.Cadence,
		arg.DayOfMonth,
		arg.AnchorDate,
		arg.Active,
		arg.ID,
	)
	return err
}
