// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_matches.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteScheduleOccurrenceMatch = `-- name: DeleteScheduleOccurrenceMatch :exec
DELETE FROM schedule_occurrence_matches
WHERE item_id = ? AND occurrence_date = ?
`

type DeleteScheduleOccurrenceMatchParams struct {
	ItemID         string
	OccurrenceDate string
}

// Drops one decision, whatever its source. Resolution uses it for a match whose
// transaction the ledger no longer holds: the decision was about a fact that is
// gone, so the occurrence returns to the timeline rather than staying hidden
// behind a row that no longer exists.
func (q *Queries) DeleteScheduleOccurrenceMatch(ctx context.Context, arg DeleteScheduleOccurrenceMatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleOccurrenceMatch, arg.ItemID, arg.OccurrenceDate)
	return err
}

const deleteScheduleOccurrenceMatchesForItem = `-- name: DeleteScheduleOccurrenceMatchesForItem :exec
DELETE FROM schedule_occurrence_matches WHERE item_id = ?
`

// Declared FKs are not enforced on this connection, so a deleted item's
// decisions are removed explicitly rather than left to the cascade.
func (q *Queries) DeleteScheduleOccurrenceMatchesForItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleOccurrenceMatchesForItem, itemID)
	return err
}

const insertAutoScheduleOccurrenceMatch = `-- name: InsertAutoScheduleOccurrenceMatch :exec
INSERT INTO schedule_occurrence_matches (item_id, occurrence_date, transaction_id, source)
VALUES (?, ?, ?, 'auto')
ON CONFLICT (item_id, occurrence_date) DO NOTHING
`

type InsertAutoScheduleOccurrenceMatchParams struct {
	ItemID         string
	OccurrenceDate string
	TransactionID  sql.NullString
}

// Resolution's decision about an occurrence nothing has been decided about yet.
// DO NOTHING rather than DO UPDATE: an existing decision is never overwritten
// here, whatever its source.
func (q *Queries) InsertAutoScheduleOccurrenceMatch(ctx context.Context, arg InsertAutoScheduleOccurrenceMatchParams) error {
	_, err := q.db.ExecContext(ctx, insertAutoScheduleOccurrenceMatch, arg.ItemID, arg.OccurrenceDate, arg.TransactionID)
	return err
}

const listLatestManualScheduleOccurrenceMatches = `-- name: ListLatestManualScheduleOccurrenceMatches :many
SELECT item_id, MAX(occurrence_date) AS occurrence_date, transaction_id
FROM schedule_occurrence_matches
WHERE source = 'manual' AND transaction_id IS NOT NULL
GROUP BY item_id
`

type ListLatestManualScheduleOccurrenceMatchesRow struct {
	ItemID         string
	OccurrenceDate interface{}
	TransactionID  sql.NullString
}

// The most recent occurrence each item has had settled by hand, which is what
// teaches that item its merchant. Only a manual decision teaches: an automatic
// match is evidence the resolver produced, and feeding it back would let one
// weak match widen the test that made it.
//
// SQLite resolves the bare transaction_id against the row MAX() selected, which
// is what makes this one row per item rather than an arbitrary pairing.
func (q *Queries) ListLatestManualScheduleOccurrenceMatches(ctx context.Context) ([]ListLatestManualScheduleOccurrenceMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestManualScheduleOccurrenceMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestManualScheduleOccurrenceMatchesRow
	for rows.Next() {
		var i ListLatestManualScheduleOccurrenceMatchesRow
		if err := rows.Scan(&i.ItemID, &i.OccurrenceDate, &i.TransactionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleOccurrenceMatchesInRange = `-- name: ListScheduleOccurrenceMatchesInRange :many
SELECT item_id, occurrence_date, transaction_id, source
FROM schedule_occurrence_matches
WHERE occurrence_date BETWEEN ? AND ?
ORDER BY item_id, occurrence_date
`

type ListScheduleOccurrenceMatchesInRangeParams struct {
	FromOccurrenceDate string
	ToOccurrenceDate   string
}

type ListScheduleOccurrenceMatchesInRangeRow struct {
	ItemID         string
	OccurrenceDate string
	TransactionID  sql.NullString
	Source         string
}

// Every decision recorded for an occurrence falling in the window, inclusive.
// Dates compare as text because they are stored as 'YYYY-MM-DD', which sorts
// chronologically.
func (q *Queries) ListScheduleOccurrenceMatchesInRange(ctx context.Context, arg ListScheduleOccurrenceMatchesInRangeParams) ([]ListScheduleOccurrenceMatchesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleOccurrenceMatchesInRange, arg.FromOccurrenceDate, arg.ToOccurrenceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleOccurrenceMatchesInRangeRow
	for rows.Next() {
		var i ListScheduleOccurrenceMatchesInRangeRow
		if err := rows.Scan(
			&i.ItemID,
			&i.OccurrenceDate,
			&i.TransactionID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettledScheduleOccurrenceMatches = `-- name: ListSettledScheduleOccurrenceMatches :many
SELECT item_id, occurrence_date, transaction_id
FROM schedule_occurrence_matches
WHERE transaction_id IS NOT NULL
`

type ListSettledScheduleOccurrenceMatchesRow struct {
	ItemID         string
	OccurrenceDate string
	TransactionID  sql.NullString
}

// Every decision that binds a transaction, with the occurrence holding it.
// Resolution seeds its claimed set from this so it never offers one row to a
// second occurrence and learns that from the partial unique index mid-pass - and
// it needs the holder, not just the id, so an occurrence is not excluded from
// its own standing match when it re-scores.
func (q *Queries) ListSettledScheduleOccurrenceMatches(ctx context.Context) ([]ListSettledScheduleOccurrenceMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettledScheduleOccurrenceMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettledScheduleOccurrenceMatchesRow
	for rows.Next() {
		var i ListSettledScheduleOccurrenceMatchesRow
		if err := rows.Scan(&i.ItemID, &i.OccurrenceDate, &i.TransactionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutoScheduleOccurrenceMatch = `-- name: UpdateAutoScheduleOccurrenceMatch :exec
UPDATE schedule_occurrence_matches
SET transaction_id = ?,
    updated_at     = CURRENT_TIMESTAMP
WHERE item_id = ? AND occurrence_date = ? AND source = 'auto'
`

type UpdateAutoScheduleOccurrenceMatchParams struct {
	TransactionID  sql.NullString
	ItemID         string
	OccurrenceDate string
}

// Supersedes an earlier *automatic* decision. The source = 'auto' guard is what
// makes "a manual decision is never overwritten by an automatic one" a property
// of the write rather than a rule each caller has to remember. An earlier
// automatic decision is freely replaced, because resolution re-resolves its
// window from scratch every pass and the later candidate is better informed.
func (q *Queries) UpdateAutoScheduleOccurrenceMatch(ctx context.Context, arg UpdateAutoScheduleOccurrenceMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateAutoScheduleOccurrenceMatch, arg.TransactionID, arg.ItemID, arg.OccurrenceDate)
	return err
}

const upsertManualScheduleOccurrenceMatch = `-- name: UpsertManualScheduleOccurrenceMatch :exec
INSERT INTO schedule_occurrence_matches (item_id, occurrence_date, transaction_id, source)
VALUES (?, ?, ?, 'manual')
ON CONFLICT (item_id, occurrence_date) DO UPDATE
SET transaction_id = excluded.transaction_id,
    source         = excluded.source,
    updated_at     = CURRENT_TIMESTAMP
`

type UpsertManualScheduleOccurrenceMatchParams struct {
	ItemID         string
	OccurrenceDate string
	TransactionID  sql.NullString
}

// The user's own decision about an occurrence: an association, or the assertion
// that nothing satisfied it. It overwrites whatever stood before, including an
// automatic match it is correcting.
func (q *Queries) UpsertManualScheduleOccurrenceMatch(ctx context.Context, arg UpsertManualScheduleOccurrenceMatchParams) error {
	_, err := q.db.ExecContext(ctx, upsertManualScheduleOccurrenceMatch, arg.ItemID, arg.OccurrenceDate, arg.TransactionID)
	return err
}
