// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_matches.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteScheduleOccurrenceMatchesForItem = `-- name: DeleteScheduleOccurrenceMatchesForItem :exec
DELETE FROM schedule_occurrence_matches WHERE item_id = ?
`

// Declared FKs are not enforced on this connection, so a deleted item's
// decisions are removed explicitly rather than left to the cascade.
func (q *Queries) DeleteScheduleOccurrenceMatchesForItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleOccurrenceMatchesForItem, itemID)
	return err
}

const insertAutoScheduleOccurrenceMatch = `-- name: InsertAutoScheduleOccurrenceMatch :exec
INSERT INTO schedule_occurrence_matches (item_id, occurrence_date, transaction_id, source)
VALUES (?, ?, ?, 'auto')
ON CONFLICT (item_id, occurrence_date) DO NOTHING
`

type InsertAutoScheduleOccurrenceMatchParams struct {
	ItemID         string
	OccurrenceDate string
	TransactionID  sql.NullString
}

// Resolution's decision about an occurrence nothing has been decided about yet.
// DO NOTHING rather than DO UPDATE: an existing decision is never overwritten
// here, whatever its source.
func (q *Queries) InsertAutoScheduleOccurrenceMatch(ctx context.Context, arg InsertAutoScheduleOccurrenceMatchParams) error {
	_, err := q.db.ExecContext(ctx, insertAutoScheduleOccurrenceMatch, arg.ItemID, arg.OccurrenceDate, arg.TransactionID)
	return err
}

const listScheduleOccurrenceMatchesInRange = `-- name: ListScheduleOccurrenceMatchesInRange :many
SELECT item_id, occurrence_date, transaction_id, source
FROM schedule_occurrence_matches
WHERE occurrence_date BETWEEN ? AND ?
ORDER BY item_id, occurrence_date
`

type ListScheduleOccurrenceMatchesInRangeParams struct {
	FromOccurrenceDate string
	ToOccurrenceDate   string
}

type ListScheduleOccurrenceMatchesInRangeRow struct {
	ItemID         string
	OccurrenceDate string
	TransactionID  sql.NullString
	Source         string
}

// Every decision recorded for an occurrence falling in the window, inclusive.
// Dates compare as text because they are stored as 'YYYY-MM-DD', which sorts
// chronologically.
func (q *Queries) ListScheduleOccurrenceMatchesInRange(ctx context.Context, arg ListScheduleOccurrenceMatchesInRangeParams) ([]ListScheduleOccurrenceMatchesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleOccurrenceMatchesInRange, arg.FromOccurrenceDate, arg.ToOccurrenceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleOccurrenceMatchesInRangeRow
	for rows.Next() {
		var i ListScheduleOccurrenceMatchesInRangeRow
		if err := rows.Scan(
			&i.ItemID,
			&i.OccurrenceDate,
			&i.TransactionID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutoScheduleOccurrenceMatch = `-- name: UpdateAutoScheduleOccurrenceMatch :exec
UPDATE schedule_occurrence_matches
SET transaction_id = ?,
    updated_at     = CURRENT_TIMESTAMP
WHERE item_id = ? AND occurrence_date = ? AND source = 'auto'
`

type UpdateAutoScheduleOccurrenceMatchParams struct {
	TransactionID  sql.NullString
	ItemID         string
	OccurrenceDate string
}

// Supersedes an earlier *automatic* decision. The source = 'auto' guard is what
// makes "a manual decision is never overwritten by an automatic one" a property
// of the write rather than a rule each caller has to remember. An earlier
// automatic decision is freely replaced, because resolution re-resolves its
// window from scratch every pass and the later candidate is better informed.
func (q *Queries) UpdateAutoScheduleOccurrenceMatch(ctx context.Context, arg UpdateAutoScheduleOccurrenceMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateAutoScheduleOccurrenceMatch, arg.TransactionID, arg.ItemID, arg.OccurrenceDate)
	return err
}

const upsertManualScheduleOccurrenceMatch = `-- name: UpsertManualScheduleOccurrenceMatch :exec
INSERT INTO schedule_occurrence_matches (item_id, occurrence_date, transaction_id, source)
VALUES (?, ?, ?, 'manual')
ON CONFLICT (item_id, occurrence_date) DO UPDATE
SET transaction_id = excluded.transaction_id,
    source         = excluded.source,
    updated_at     = CURRENT_TIMESTAMP
`

type UpsertManualScheduleOccurrenceMatchParams struct {
	ItemID         string
	OccurrenceDate string
	TransactionID  sql.NullString
}

// The user's own decision about an occurrence: an association, or the assertion
// that nothing satisfied it. It overwrites whatever stood before, including an
// automatic match it is correcting.
func (q *Queries) UpsertManualScheduleOccurrenceMatch(ctx context.Context, arg UpsertManualScheduleOccurrenceMatchParams) error {
	_, err := q.db.ExecContext(ctx, upsertManualScheduleOccurrenceMatch, arg.ItemID, arg.OccurrenceDate, arg.TransactionID)
	return err
}
