// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sweep.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getLatestSweepRecommendation = `-- name: GetLatestSweepRecommendation :one
SELECT id, kind, current_checking, current_savings, savings_unknown, total_spending_budget, mtd_spending, savings_target, mtd_savings_contributed, reserve, fixed_safety_margin, suggested_sweep, direction, reasons, created_at, updated_at FROM sweep_recommendation
WHERE id = ?
`

func (q *Queries) GetLatestSweepRecommendation(ctx context.Context, id string) (SweepRecommendation, error) {
	row := q.db.QueryRowContext(ctx, getLatestSweepRecommendation, id)
	var i SweepRecommendation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CurrentChecking,
		&i.CurrentSavings,
		&i.SavingsUnknown,
		&i.TotalSpendingBudget,
		&i.MtdSpending,
		&i.SavingsTarget,
		&i.MtdSavingsContributed,
		&i.Reserve,
		&i.FixedSafetyMargin,
		&i.SuggestedSweep,
		&i.Direction,
		&i.Reasons,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSweepRecommendation = `-- name: UpsertSweepRecommendation :exec
INSERT INTO sweep_recommendation (
    id,
    kind,
    current_checking,
    current_savings,
    savings_unknown,
    total_spending_budget,
    mtd_spending,
    savings_target,
    mtd_savings_contributed,
    reserve,
    fixed_safety_margin,
    suggested_sweep,
    direction,
    reasons
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    kind                    = excluded.kind,
    current_checking        = excluded.current_checking,
    current_savings         = excluded.current_savings,
    savings_unknown         = excluded.savings_unknown,
    total_spending_budget   = excluded.total_spending_budget,
    mtd_spending            = excluded.mtd_spending,
    savings_target          = excluded.savings_target,
    mtd_savings_contributed = excluded.mtd_savings_contributed,
    reserve                 = excluded.reserve,
    fixed_safety_margin     = excluded.fixed_safety_margin,
    suggested_sweep         = excluded.suggested_sweep,
    direction               = excluded.direction,
    reasons                 = excluded.reasons,
    updated_at              = CURRENT_TIMESTAMP
`

type UpsertSweepRecommendationParams struct {
	ID                    string
	Kind                  string
	CurrentChecking       sql.NullFloat64
	CurrentSavings        sql.NullFloat64
	SavingsUnknown        int64
	TotalSpendingBudget   float64
	MtdSpending           float64
	SavingsTarget         float64
	MtdSavingsContributed float64
	Reserve               float64
	FixedSafetyMargin     float64
	SuggestedSweep        float64
	Direction             string
	Reasons               string
}

func (q *Queries) UpsertSweepRecommendation(ctx context.Context, arg UpsertSweepRecommendationParams) error {
	_, err := q.db.ExecContext(ctx, upsertSweepRecommendation,
		arg.ID,
		arg.Kind,
		arg.CurrentChecking,
		arg.CurrentSavings,
		arg.SavingsUnknown,
		arg.TotalSpendingBudget,
		arg.MtdSpending,
		arg.SavingsTarget,
		arg.MtdSavingsContributed,
		arg.Reserve,
		arg.FixedSafetyMargin,
		arg.SuggestedSweep,
		arg.Direction,
		arg.Reasons,
	)
	return err
}
