// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sweep.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getLatestSweepRecommendation = `-- name: GetLatestSweepRecommendation :one
SELECT id, kind, current_checking, current_savings, savings_unknown, required_checking, fixed_safety_margin, suggested_sweep, direction, reasons, timeline, computed_at, created_at, updated_at FROM sweep_recommendation
ORDER BY computed_at DESC, rowid DESC
LIMIT 1
`

func (q *Queries) GetLatestSweepRecommendation(ctx context.Context) (SweepRecommendation, error) {
	row := q.db.QueryRowContext(ctx, getLatestSweepRecommendation)
	var i SweepRecommendation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CurrentChecking,
		&i.CurrentSavings,
		&i.SavingsUnknown,
		&i.RequiredChecking,
		&i.FixedSafetyMargin,
		&i.SuggestedSweep,
		&i.Direction,
		&i.Reasons,
		&i.Timeline,
		&i.ComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSweepRecommendationByID = `-- name: GetSweepRecommendationByID :one
SELECT id, kind, current_checking, current_savings, savings_unknown, required_checking, fixed_safety_margin, suggested_sweep, direction, reasons, timeline, computed_at, created_at, updated_at FROM sweep_recommendation
WHERE id = ?
`

func (q *Queries) GetSweepRecommendationByID(ctx context.Context, id string) (SweepRecommendation, error) {
	row := q.db.QueryRowContext(ctx, getSweepRecommendationByID, id)
	var i SweepRecommendation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CurrentChecking,
		&i.CurrentSavings,
		&i.SavingsUnknown,
		&i.RequiredChecking,
		&i.FixedSafetyMargin,
		&i.SuggestedSweep,
		&i.Direction,
		&i.Reasons,
		&i.Timeline,
		&i.ComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSweepRecommendation = `-- name: InsertSweepRecommendation :exec
INSERT INTO sweep_recommendation (
    id,
    kind,
    current_checking,
    current_savings,
    savings_unknown,
    required_checking,
    fixed_safety_margin,
    suggested_sweep,
    direction,
    reasons,
    timeline,
    computed_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertSweepRecommendationParams struct {
	ID                string
	Kind              string
	CurrentChecking   sql.NullFloat64
	CurrentSavings    sql.NullFloat64
	SavingsUnknown    int64
	RequiredChecking  float64
	FixedSafetyMargin float64
	SuggestedSweep    float64
	Direction         string
	Reasons           string
	Timeline          string
	ComputedAt        time.Time
}

func (q *Queries) InsertSweepRecommendation(ctx context.Context, arg InsertSweepRecommendationParams) error {
	_, err := q.db.ExecContext(ctx, insertSweepRecommendation,
		arg.ID,
		arg.Kind,
		arg.CurrentChecking,
		arg.CurrentSavings,
		arg.SavingsUnknown,
		arg.RequiredChecking,
		arg.FixedSafetyMargin,
		arg.SuggestedSweep,
		arg.Direction,
		arg.Reasons,
		arg.Timeline,
		arg.ComputedAt,
	)
	return err
}

const listSweepRecommendations = `-- name: ListSweepRecommendations :many
SELECT id, kind, current_checking, current_savings, savings_unknown, required_checking, fixed_safety_margin, suggested_sweep, direction, reasons, timeline, computed_at, created_at, updated_at FROM sweep_recommendation
ORDER BY computed_at DESC, rowid DESC
`

func (q *Queries) ListSweepRecommendations(ctx context.Context) ([]SweepRecommendation, error) {
	rows, err := q.db.QueryContext(ctx, listSweepRecommendations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweepRecommendation
	for rows.Next() {
		var i SweepRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CurrentChecking,
			&i.CurrentSavings,
			&i.SavingsUnknown,
			&i.RequiredChecking,
			&i.FixedSafetyMargin,
			&i.SuggestedSweep,
			&i.Direction,
			&i.Reasons,
			&i.Timeline,
			&i.ComputedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
