// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const earliestTransactionDate = `-- name: EarliestTransactionDate :one
SELECT date FROM transactions
ORDER BY date ASC, id ASC
LIMIT 1
`

func (q *Queries) EarliestTransactionDate(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, earliestTransactionDate)
	var date time.Time
	err := row.Scan(&date)
	return date, err
}

const getRecentTransaction = `-- name: GetRecentTransaction :one
SELECT t.id, t.account_id, t.date, t.amount_amount, t.amount_currency, t.merchant, t.counterparty, t.category_primary, t.category_detailed, t.status, t.created_at, t.updated_at, t.classification, t.category_id, t.categorization_overridden, t.transfer_destination_account_id, t.transfer_subtype, t.transfer_destination_overridden, a.name AS account_name, c.name AS category_name, da.name AS destination_account_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN accounts da ON da.id = t.transfer_destination_account_id
WHERE t.id = ?
`

type GetRecentTransactionRow struct {
	Transaction            Transaction
	AccountName            string
	CategoryName           sql.NullString
	DestinationAccountName sql.NullString
}

func (q *Queries) GetRecentTransaction(ctx context.Context, id string) (GetRecentTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getRecentTransaction, id)
	var i GetRecentTransactionRow
	err := row.Scan(
		&i.Transaction.ID,
		&i.Transaction.AccountID,
		&i.Transaction.Date,
		&i.Transaction.AmountAmount,
		&i.Transaction.AmountCurrency,
		&i.Transaction.Merchant,
		&i.Transaction.Counterparty,
		&i.Transaction.CategoryPrimary,
		&i.Transaction.CategoryDetailed,
		&i.Transaction.Status,
		&i.Transaction.CreatedAt,
		&i.Transaction.UpdatedAt,
		&i.Transaction.Classification,
		&i.Transaction.CategoryID,
		&i.Transaction.CategorizationOverridden,
		&i.Transaction.TransferDestinationAccountID,
		&i.Transaction.TransferSubtype,
		&i.Transaction.TransferDestinationOverridden,
		&i.AccountName,
		&i.CategoryName,
		&i.DestinationAccountName,
	)
	return i, err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT cursor FROM transaction_sync_state
WHERE connection_id = ?
`

func (q *Queries) GetSyncCursor(ctx context.Context, connectionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, connectionID)
	var cursor string
	err := row.Scan(&cursor)
	return cursor, err
}

const getTransactionForCategorization = `-- name: GetTransactionForCategorization :one
SELECT id,
       merchant,
       counterparty,
       category_primary,
       category_detailed,
       amount_amount,
       amount_currency,
       classification,
       category_id,
       categorization_overridden
FROM transactions
WHERE id = ?
`

type GetTransactionForCategorizationRow struct {
	ID                       string
	Merchant                 string
	Counterparty             string
	CategoryPrimary          string
	CategoryDetailed         string
	AmountAmount             float64
	AmountCurrency           string
	Classification           string
	CategoryID               sql.NullString
	CategorizationOverridden int64
}

// The fields the categorization engine needs to (re-)resolve one transaction,
// plus its current categorization facet so callers can skip overridden / already
// categorized rows.
func (q *Queries) GetTransactionForCategorization(ctx context.Context, id string) (GetTransactionForCategorizationRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionForCategorization, id)
	var i GetTransactionForCategorizationRow
	err := row.Scan(
		&i.ID,
		&i.Merchant,
		&i.Counterparty,
		&i.CategoryPrimary,
		&i.CategoryDetailed,
		&i.AmountAmount,
		&i.AmountCurrency,
		&i.Classification,
		&i.CategoryID,
		&i.CategorizationOverridden,
	)
	return i, err
}

const getTransactionTransferDestination = `-- name: GetTransactionTransferDestination :one
SELECT transfer_destination_account_id,
       transfer_subtype,
       transfer_destination_overridden
FROM transactions
WHERE id = ?
`

type GetTransactionTransferDestinationRow struct {
	TransferDestinationAccountID  sql.NullString
	TransferSubtype               string
	TransferDestinationOverridden int64
}

// The stored transfer facet of one transaction: the destination account, the
// subtype, and the override flag.
func (q *Queries) GetTransactionTransferDestination(ctx context.Context, id string) (GetTransactionTransferDestinationRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionTransferDestination, id)
	var i GetTransactionTransferDestinationRow
	err := row.Scan(&i.TransferDestinationAccountID, &i.TransferSubtype, &i.TransferDestinationOverridden)
	return i, err
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT t.id, t.account_id, t.date, t.amount_amount, t.amount_currency, t.merchant, t.counterparty, t.category_primary, t.category_detailed, t.status, t.created_at, t.updated_at, t.classification, t.category_id, t.categorization_overridden, t.transfer_destination_account_id, t.transfer_subtype, t.transfer_destination_overridden, a.name AS account_name, c.name AS category_name, da.name AS destination_account_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN accounts da ON da.id = t.transfer_destination_account_id
ORDER BY t.date DESC, t.id DESC
LIMIT ?
`

type ListRecentTransactionsRow struct {
	Transaction            Transaction
	AccountName            string
	CategoryName           sql.NullString
	DestinationAccountName sql.NullString
}

func (q *Queries) ListRecentTransactions(ctx context.Context, limit int64) ([]ListRecentTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentTransactionsRow
	for rows.Next() {
		var i ListRecentTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.AccountID,
			&i.Transaction.Date,
			&i.Transaction.AmountAmount,
			&i.Transaction.AmountCurrency,
			&i.Transaction.Merchant,
			&i.Transaction.Counterparty,
			&i.Transaction.CategoryPrimary,
			&i.Transaction.CategoryDetailed,
			&i.Transaction.Status,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.Classification,
			&i.Transaction.CategoryID,
			&i.Transaction.CategorizationOverridden,
			&i.Transaction.TransferDestinationAccountID,
			&i.Transaction.TransferSubtype,
			&i.Transaction.TransferDestinationOverridden,
			&i.AccountName,
			&i.CategoryName,
			&i.DestinationAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpendingTransactionsInRange = `-- name: ListSpendingTransactionsInRange :many
SELECT t.id, t.account_id, t.date, t.amount_amount, t.amount_currency, t.merchant, t.counterparty, t.category_primary, t.category_detailed, t.status, t.created_at, t.updated_at, t.classification, t.category_id, t.categorization_overridden, t.transfer_destination_account_id, t.transfer_subtype, t.transfer_destination_overridden, a.name AS account_name, c.name AS category_name, da.name AS destination_account_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN accounts da ON da.id = t.transfer_destination_account_id
WHERE t.classification = 'spending' AND t.date >= ? AND t.date < ?
ORDER BY t.date DESC, t.id DESC
`

type ListSpendingTransactionsInRangeParams struct {
	Date   time.Time
	Date_2 time.Time
}

type ListSpendingTransactionsInRangeRow struct {
	Transaction            Transaction
	AccountName            string
	CategoryName           sql.NullString
	DestinationAccountName sql.NullString
}

// The Spending transactions whose date falls in [start, end), newest-first, with
// the same display joins as ListRecentTransactions. Scoping to one month's
// Spending is exactly the set the wrap's spend-by-Category aggregates, so the
// drill-down list reconciles to the figure it was reached from.
func (q *Queries) ListSpendingTransactionsInRange(ctx context.Context, arg ListSpendingTransactionsInRangeParams) ([]ListSpendingTransactionsInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpendingTransactionsInRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpendingTransactionsInRangeRow
	for rows.Next() {
		var i ListSpendingTransactionsInRangeRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.AccountID,
			&i.Transaction.Date,
			&i.Transaction.AmountAmount,
			&i.Transaction.AmountCurrency,
			&i.Transaction.Merchant,
			&i.Transaction.Counterparty,
			&i.Transaction.CategoryPrimary,
			&i.Transaction.CategoryDetailed,
			&i.Transaction.Status,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.Classification,
			&i.Transaction.CategoryID,
			&i.Transaction.CategorizationOverridden,
			&i.Transaction.TransferDestinationAccountID,
			&i.Transaction.TransferSubtype,
			&i.Transaction.TransferDestinationOverridden,
			&i.AccountName,
			&i.CategoryName,
			&i.DestinationAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsFiltered = `-- name: ListTransactionsFiltered :many
SELECT t.id, t.account_id, t.date, t.amount_amount, t.amount_currency, t.merchant, t.counterparty, t.category_primary, t.category_detailed, t.status, t.created_at, t.updated_at, t.classification, t.category_id, t.categorization_overridden, t.transfer_destination_account_id, t.transfer_subtype, t.transfer_destination_overridden, a.name AS account_name, c.name AS category_name, da.name AS destination_account_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
LEFT JOIN categories c ON c.id = t.category_id
LEFT JOIN accounts da ON da.id = t.transfer_destination_account_id
WHERE (?1 IS NULL OR t.merchant LIKE '%' || ?1 || '%')
  AND (
    CAST(?2 AS INTEGER) = 0
    OR t.classification = 'needs_review'
    OR (t.classification = 'spending' AND t.category_id IS NULL)
    OR (t.classification = 'transfer'
        AND t.amount_amount > 0
        AND t.transfer_destination_account_id IS NULL
        AND t.transfer_destination_overridden = 0)
  )
ORDER BY t.date DESC, t.id DESC
`

type ListTransactionsFilteredParams struct {
	Merchant       interface{}
	NeedsAttention int64
}

type ListTransactionsFilteredRow struct {
	Transaction            Transaction
	AccountName            string
	CategoryName           sql.NullString
	DestinationAccountName sql.NullString
}

// The full-history filtered activity read backing the /transactions view search
// and needs-attention filter. Unlike ListRecentTransactions it applies no recent
// cap - an active filter sees the whole history. Both filters are optional and
// compose: a NULL merchant skips the merchant match; a zero needs_attention skips
// the needs-attention predicate. needs-attention is the union of an unresolved
// inflow (needs_review), uncategorized Spending (spending with no Category), and
// an unknown-destination outflow Transfer - the unknown predicate mirrors the
// recentFrom TransferDestinationUnknown rule exactly (see docs/domain/README.md).
// Same display joins and ordering as ListRecentTransactions.
func (q *Queries) ListTransactionsFiltered(ctx context.Context, arg ListTransactionsFilteredParams) ([]ListTransactionsFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsFiltered, arg.Merchant, arg.NeedsAttention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsFilteredRow
	for rows.Next() {
		var i ListTransactionsFilteredRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.AccountID,
			&i.Transaction.Date,
			&i.Transaction.AmountAmount,
			&i.Transaction.AmountCurrency,
			&i.Transaction.Merchant,
			&i.Transaction.Counterparty,
			&i.Transaction.CategoryPrimary,
			&i.Transaction.CategoryDetailed,
			&i.Transaction.Status,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.Classification,
			&i.Transaction.CategoryID,
			&i.Transaction.CategorizationOverridden,
			&i.Transaction.TransferDestinationAccountID,
			&i.Transaction.TransferSubtype,
			&i.Transaction.TransferDestinationOverridden,
			&i.AccountName,
			&i.CategoryName,
			&i.DestinationAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForCategorization = `-- name: ListTransactionsForCategorization :many
SELECT id,
       merchant,
       counterparty,
       category_primary,
       category_detailed,
       amount_amount,
       amount_currency,
       classification,
       category_id,
       categorization_overridden
FROM transactions
`

type ListTransactionsForCategorizationRow struct {
	ID                       string
	Merchant                 string
	Counterparty             string
	CategoryPrimary          string
	CategoryDetailed         string
	AmountAmount             float64
	AmountCurrency           string
	Classification           string
	CategoryID               sql.NullString
	CategorizationOverridden int64
}

// Every transaction's categorization inputs and current facet, for the
// rule-change re-categorization pass (which filters and re-resolves in Go).
func (q *Queries) ListTransactionsForCategorization(ctx context.Context) ([]ListTransactionsForCategorizationRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsForCategorization)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsForCategorizationRow
	for rows.Next() {
		var i ListTransactionsForCategorizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Merchant,
			&i.Counterparty,
			&i.CategoryPrimary,
			&i.CategoryDetailed,
			&i.AmountAmount,
			&i.AmountCurrency,
			&i.Classification,
			&i.CategoryID,
			&i.CategorizationOverridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferLegs = `-- name: ListTransferLegs :many
SELECT t.id,
       t.account_id,
       t.amount_amount,
       t.date,
       t.classification,
       t.transfer_destination_overridden
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.classification = 'transfer'
  AND a.state != 'closed'
`

type ListTransferLegsRow struct {
	ID                            string
	AccountID                     string
	AmountAmount                  float64
	Date                          time.Time
	Classification                string
	TransferDestinationOverridden int64
}

// Every stored Transfer leg on a connected (non-closed) account, with the fields
// the auto-pairing pass needs: the caller filters outflow source legs and the
// inflow candidates from this set, pairs them by amount + date window, and skips
// legs whose transfer facet is overridden.
func (q *Queries) ListTransferLegs(ctx context.Context) ([]ListTransferLegsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransferLegs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferLegsRow
	for rows.Next() {
		var i ListTransferLegsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AmountAmount,
			&i.Date,
			&i.Classification,
			&i.TransferDestinationOverridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncategorizedForCategorization = `-- name: ListUncategorizedForCategorization :many
SELECT id,
       merchant,
       counterparty,
       category_primary,
       category_detailed,
       amount_amount,
       amount_currency,
       classification,
       category_id,
       categorization_overridden
FROM transactions
WHERE classification = '' AND categorization_overridden = 0
`

type ListUncategorizedForCategorizationRow struct {
	ID                       string
	Merchant                 string
	Counterparty             string
	CategoryPrimary          string
	CategoryDetailed         string
	AmountAmount             float64
	AmountCurrency           string
	Classification           string
	CategoryID               sql.NullString
	CategorizationOverridden int64
}

// The categorization inputs for every transaction still at the uncategorized
// default (classification = ”) and not manually overridden. This is the
// self-healing sweep's candidate set: rows a prior sync left uncategorized (synced
// before categorization ran, or after a categorize error that still advanced the
// cursor) that a later sync must resolve even though they are not in the current
// pull's delta. Categorized rows (any non-empty classification) are out of scope.
func (q *Queries) ListUncategorizedForCategorization(ctx context.Context) ([]ListUncategorizedForCategorizationRow, error) {
	rows, err := q.db.QueryContext(ctx, listUncategorizedForCategorization)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUncategorizedForCategorizationRow
	for rows.Next() {
		var i ListUncategorizedForCategorizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Merchant,
			&i.Counterparty,
			&i.CategoryPrimary,
			&i.CategoryDetailed,
			&i.AmountAmount,
			&i.AmountCurrency,
			&i.Classification,
			&i.CategoryID,
			&i.CategorizationOverridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overrideTransactionCategorization = `-- name: OverrideTransactionCategorization :exec
UPDATE transactions
SET classification            = ?,
    category_id               = ?,
    categorization_overridden = 1,
    updated_at                = CURRENT_TIMESTAMP
WHERE id = ?
`

type OverrideTransactionCategorizationParams struct {
	Classification string
	CategoryID     sql.NullString
	ID             string
}

// Write a manual re-categorization and mark the row overridden, so it beats
// auto-resolution and survives re-sync.
func (q *Queries) OverrideTransactionCategorization(ctx context.Context, arg OverrideTransactionCategorizationParams) error {
	_, err := q.db.ExecContext(ctx, overrideTransactionCategorization, arg.Classification, arg.CategoryID, arg.ID)
	return err
}

const overrideTransactionTransferDestination = `-- name: OverrideTransactionTransferDestination :exec
UPDATE transactions
SET transfer_destination_account_id = ?,
    transfer_subtype                = ?,
    transfer_destination_overridden = 1,
    updated_at                      = CURRENT_TIMESTAMP
WHERE id = ?
`

type OverrideTransactionTransferDestinationParams struct {
	TransferDestinationAccountID sql.NullString
	TransferSubtype              string
	ID                           string
}

// Write a manual transfer-destination choice and mark the row's transfer facet
// overridden, so it beats auto-pairing and survives re-sync. Independent of the
// categorization override.
func (q *Queries) OverrideTransactionTransferDestination(ctx context.Context, arg OverrideTransactionTransferDestinationParams) error {
	_, err := q.db.ExecContext(ctx, overrideTransactionTransferDestination, arg.TransferDestinationAccountID, arg.TransferSubtype, arg.ID)
	return err
}

const setTransactionCategorization = `-- name: SetTransactionCategorization :exec

UPDATE transactions
SET classification = ?,
    category_id    = ?,
    updated_at     = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetTransactionCategorizationParams struct {
	Classification string
	CategoryID     sql.NullString
	ID             string
}

// The categorization columns (classification, category_id, categorization_overridden)
// are deliberately absent from both the insert column list and the ON CONFLICT
// update: categorization is owned separately, so a new row takes the column
// defaults and an existing row keeps whatever categorization it already carries.
// Write the auto-resolved categorization for a transaction. It never touches the
// override flag, so a row's sticky facet is preserved; callers pre-skip overridden
// rows.
func (q *Queries) SetTransactionCategorization(ctx context.Context, arg SetTransactionCategorizationParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionCategorization, arg.Classification, arg.CategoryID, arg.ID)
	return err
}

const setTransactionTransferDestination = `-- name: SetTransactionTransferDestination :exec
UPDATE transactions
SET transfer_destination_account_id = ?,
    transfer_subtype                = ?,
    updated_at                      = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetTransactionTransferDestinationParams struct {
	TransferDestinationAccountID sql.NullString
	TransferSubtype              string
	ID                           string
}

// Write the auto-paired transfer destination + subtype for a transaction. It
// never touches the override flag, so a row's sticky transfer facet is preserved;
// callers pre-skip overridden rows.
func (q *Queries) SetTransactionTransferDestination(ctx context.Context, arg SetTransactionTransferDestinationParams) error {
	_, err := q.db.ExecContext(ctx, setTransactionTransferDestination, arg.TransferDestinationAccountID, arg.TransferSubtype, arg.ID)
	return err
}

const transactionsInRange = `-- name: TransactionsInRange :many
SELECT id,
       date,
       amount_amount,
       amount_currency,
       classification,
       category_id,
       transfer_subtype,
       status
FROM transactions
WHERE date >= ? AND date < ?
ORDER BY date, id
`

type TransactionsInRangeParams struct {
	Date   time.Time
	Date_2 time.Time
}

type TransactionsInRangeRow struct {
	ID              string
	Date            time.Time
	AmountAmount    float64
	AmountCurrency  string
	Classification  string
	CategoryID      sql.NullString
	TransferSubtype string
	Status          string
}

func (q *Queries) TransactionsInRange(ctx context.Context, arg TransactionsInRangeParams) ([]TransactionsInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, transactionsInRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionsInRangeRow
	for rows.Next() {
		var i TransactionsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountAmount,
			&i.AmountCurrency,
			&i.Classification,
			&i.CategoryID,
			&i.TransferSubtype,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO transaction_sync_state (
    connection_id, cursor
) VALUES (
    ?, ?
)
ON CONFLICT (connection_id) DO UPDATE SET
    cursor     = excluded.cursor,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSyncCursorParams struct {
	ConnectionID string
	Cursor       string
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncCursor, arg.ConnectionID, arg.Cursor)
	return err
}

const upsertTransaction = `-- name: UpsertTransaction :exec
INSERT INTO transactions (
    id,
    account_id,
    date,
    amount_amount,
    amount_currency,
    merchant,
    counterparty,
    category_primary,
    category_detailed,
    status
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (id) DO UPDATE SET
    account_id        = excluded.account_id,
    date              = excluded.date,
    amount_amount     = excluded.amount_amount,
    amount_currency   = excluded.amount_currency,
    merchant          = excluded.merchant,
    counterparty      = excluded.counterparty,
    category_primary  = excluded.category_primary,
    category_detailed = excluded.category_detailed,
    status            = excluded.status,
    updated_at        = CURRENT_TIMESTAMP
`

type UpsertTransactionParams struct {
	ID               string
	AccountID        string
	Date             time.Time
	AmountAmount     float64
	AmountCurrency   string
	Merchant         string
	Counterparty     string
	CategoryPrimary  string
	CategoryDetailed string
	Status           string
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTransaction,
		arg.ID,
		arg.AccountID,
		arg.Date,
		arg.AmountAmount,
		arg.AmountCurrency,
		arg.Merchant,
		arg.Counterparty,
		arg.CategoryPrimary,
		arg.CategoryDetailed,
		arg.Status,
	)
	return err
}
