// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"
	"time"
)

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT cursor FROM transaction_sync_state
WHERE connection_id = ?
`

func (q *Queries) GetSyncCursor(ctx context.Context, connectionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, connectionID)
	var cursor string
	err := row.Scan(&cursor)
	return cursor, err
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT t.id, t.account_id, t.date, t.amount_amount, t.amount_currency, t.merchant, t.counterparty, t.category_primary, t.category_detailed, t.status, t.created_at, t.updated_at, a.name AS account_name
FROM transactions t
JOIN accounts a ON a.id = t.account_id
ORDER BY t.date DESC, t.id DESC
LIMIT ?
`

type ListRecentTransactionsRow struct {
	Transaction Transaction
	AccountName string
}

func (q *Queries) ListRecentTransactions(ctx context.Context, limit int64) ([]ListRecentTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentTransactionsRow
	for rows.Next() {
		var i ListRecentTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.AccountID,
			&i.Transaction.Date,
			&i.Transaction.AmountAmount,
			&i.Transaction.AmountCurrency,
			&i.Transaction.Merchant,
			&i.Transaction.Counterparty,
			&i.Transaction.CategoryPrimary,
			&i.Transaction.CategoryDetailed,
			&i.Transaction.Status,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO transaction_sync_state (
    connection_id, cursor
) VALUES (
    ?, ?
)
ON CONFLICT (connection_id) DO UPDATE SET
    cursor     = excluded.cursor,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSyncCursorParams struct {
	ConnectionID string
	Cursor       string
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncCursor, arg.ConnectionID, arg.Cursor)
	return err
}

const upsertTransaction = `-- name: UpsertTransaction :exec
INSERT INTO transactions (
    id,
    account_id,
    date,
    amount_amount,
    amount_currency,
    merchant,
    counterparty,
    category_primary,
    category_detailed,
    status
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (id) DO UPDATE SET
    account_id        = excluded.account_id,
    date              = excluded.date,
    amount_amount     = excluded.amount_amount,
    amount_currency   = excluded.amount_currency,
    merchant          = excluded.merchant,
    counterparty      = excluded.counterparty,
    category_primary  = excluded.category_primary,
    category_detailed = excluded.category_detailed,
    status            = excluded.status,
    updated_at        = CURRENT_TIMESTAMP
`

type UpsertTransactionParams struct {
	ID               string
	AccountID        string
	Date             time.Time
	AmountAmount     float64
	AmountCurrency   string
	Merchant         string
	Counterparty     string
	CategoryPrimary  string
	CategoryDetailed string
	Status           string
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTransaction,
		arg.ID,
		arg.AccountID,
		arg.Date,
		arg.AmountAmount,
		arg.AmountCurrency,
		arg.Merchant,
		arg.Counterparty,
		arg.CategoryPrimary,
		arg.CategoryDetailed,
		arg.Status,
	)
	return err
}
